export const products = [
{
  productId: 1,
  menu: 'ディナーメニュー',
  category: 'メイン料理',
  subCategory: '肉料理',
  productName: 'ポークチョップ',
  price: 3000,
  cost: 1200,
  profit: 1800,
},
{
  productId: 2,
  menu: 'ディナーメニュー',
  category: 'メイン料理',
  subCategory: '肉料理',
  productName: 'サーロインステーキ',
  price: 4500,
  cost: 1800,
  profit: 2700,
},
{
  productId: 3,
  menu: 'ディナーメニュー',
  category: 'メイン料理',
  subCategory: '肉料理',
  productName: 'グリルチキン',
  price: 2500,
  cost: 1000,
  profit: 1500,
},
{
  productId: 4,
  menu: 'ディナーメニュー',
  category: 'メイン料理',
  subCategory: '肉料理',
  productName: 'ラムチョップ',
  price: 4200,
  cost: 1680,
  profit: 2520,
},
{
  productId: 5,
  menu: 'ディナーメニュー',
  category: 'メイン料理',
  subCategory: '肉料理',
  productName: 'ローストビーフ',
  price: 3800,
  cost: 1520,
  profit: 2280,
},
{
  productId: 6,
  menu: 'ディナーメニュー',
  category: 'メイン料理',
  subCategory: '肉料理',
  productName: 'スペアリブ',
  price: 3200,
  cost: 1280,
  profit: 1920,
},
{
  productId: 7,
  menu: 'ディナーメニュー',
  category: 'メイン料理',
  subCategory: '魚料理',
  productName: 'サーモングリル',
  price: 2800,
  cost: 1120,
  profit: 1680,
},
{
  productId: 8,
  menu: 'ディナーメニュー',
  category: 'メイン料理',
  subCategory: '魚料理',
  productName: 'マグロステーキ',
  price: 3400,
  cost: 1360,
  profit: 2040,
},
{
  productId: 9,
  menu: 'ディナーメニュー',
  category: 'メイン料理',
  subCategory: '魚料理',
  productName: 'エビ天ぷら',
  price: 2600,
  cost: 1040,
  profit: 1560,
},
{
  productId: 10,
  menu: 'ディナーメニュー',
  category: 'メイン料理',
  subCategory: '魚料理',
  productName: '鯖の味噌煮',
  price: 2000,
  cost: 800,
  profit: 1200,
},
{
  productId: 11,
  menu: 'ディナーメニュー',
  category: 'メイン料理',
  subCategory: 'カレー料理',
  productName: 'チキンカレー',
  price: 2000,
  cost: 800,
  profit: 1200,
},
{
  productId: 12,
  menu: 'ディナーメニュー',
  category: 'メイン料理',
  subCategory: 'カレー料理',
  productName: 'ベジタブルカレー',
  price: 1500,
  cost: 600,
  profit: 900,
},
{
  productId: 13,
  menu: 'ディナーメニュー',
  category: 'メイン料理',
  subCategory: 'カレー料理',
  productName: 'ビーフカレー',
  price: 2200,
  cost: 880,
  profit: 1320,
},
{
  productId: 14,
  menu: 'ディナーメニュー',
  category: 'メイン料理',
  subCategory: 'カレー料理',
  productName: 'シーフードカレー',
  price: 2400,
  cost: 960,
  profit: 1440,
},
{
  productId: 15,
  menu: 'ディナーメニュー',
  category: 'メイン料理',
  subCategory: 'カレー料理',
  productName: 'キーマカレー',
  price: 2100,
  cost: 840,
  profit: 1260,
},
{
  productId: 16,
  menu: 'ディナーメニュー',
  category: 'メイン料理',
  subCategory: 'パスタ料理',
  productName: 'ボロネーゼ',
  price: 1900,
  cost: 760,
  profit: 1140,
},
{
  productId: 17,
  menu: 'ディナーメニュー',
  category: 'メイン料理',
  subCategory: 'パスタ料理',
  productName: 'カルボナーラ',
  price: 2000,
  cost: 800,
  profit: 1200,
},
{
  productId: 18,
  menu: 'ディナーメニュー',
  category: 'メイン料理',
  subCategory: 'パスタ料理',
  productName: 'シーフードパスタ',
  price: 2300,
  cost: 920,
  profit: 1380,
},
{
  productId: 19,
  menu: 'ディナーメニュー',
  category: 'サラダ',
  subCategory: '野菜サラダ',
  productName: 'シーザーサラダ',
  price: 1200,
  cost: 480,
  profit: 720,
},
{
  productId: 20,
  menu: 'ディナーメニュー',
  category: 'サラダ',
  subCategory: '野菜サラダ',
  productName: 'ギリシャサラダ',
  price: 1100,
  cost: 440,
  profit: 660,
},
{
  productId: 21,
  menu: 'ディナーメニュー',
  category: 'サラダ',
  subCategory: '野菜サラダ',
  productName: 'ミックスグリーンサラダ',
  price: 1000,
  cost: 400,
  profit: 600,
},
{
  productId: 22,
  menu: 'ディナーメニュー',
  category: 'サラダ',
  subCategory: '穀物サラダ',
  productName: 'キヌアサラダ',
  price: 1300,
  cost: 520,
  profit: 780,
},
{
  productId: 23,
  menu: 'ディナーメニュー',
  category: 'デザート',
  subCategory: 'ケーキ',
  productName: 'チーズケーキ',
  price: 900,
  cost: 360,
  profit: 540,
},
{
  productId: 24,
  menu: 'ディナーメニュー',
  category: 'デザート',
  subCategory: 'ケーキ',
  productName: 'チョコレートラバケーキ',
  price: 1000,
  cost: 400,
  profit: 600,
},
{
  productId: 25,
  menu: 'ディナーメニュー',
  category: 'ドリンク',
  subCategory: 'アルコール',
  productName: 'ビール',
  price: 1000,
  cost: 400,
  profit: 600,
},
{
  productId: 26,
  menu: 'ディナーメニュー',
  category: 'ドリンク',
  subCategory: 'アルコール',
  productName: '赤ワイン',
  price: 1500,
  cost: 600,
  profit: 900,
},
{
  productId: 27,
  menu: 'ディナーメニュー',
  category: 'ドリンク',
  subCategory: 'アルコール',
  productName: '白ワイン',
  price: 1500,
  cost: 600,
  profit: 900,
},
{
  productId: 28,
  menu: 'ディナーメニュー',
  category: 'ドリンク',
  subCategory: 'アルコール',
  productName: 'ウイスキー',
  price: 1200,
  cost: 480,
  profit: 720,
},
{
  productId: 29,
  menu: 'ディナーメニュー',
  category: 'ドリンク',
  subCategory: 'ソフトドリンク',
  productName: 'コーラ',
  price: 600,
  cost: 240,
  profit: 360,
},
{
  productId: 30,
  menu: 'ディナーメニュー',
  category: 'ドリンク',
  subCategory: 'ソフトドリンク',
  productName: 'オレンジジュース',
  price: 600,
  cost: 240,
  profit: 360,
},
{
  productId: 31,
  menu: 'ランチメニュー',
  category: 'メイン料理',
  subCategory: '肉料理',
  productName: 'ポークカツ定食',
  price: 1500,
  cost: 600,
  profit: 900,
},
{
  productId: 32,
  menu: 'ランチメニュー',
  category: 'メイン料理',
  subCategory: '肉料理',
  productName: 'チキン照り焼き',
  price: 1300,
  cost: 520,
  profit: 780,
},
{
  productId: 33,
  menu: 'ランチメニュー',
  category: 'メイン料理',
  subCategory: '肉料理',
  productName: 'ハンバーグランチ',
  price: 1400,
  cost: 560,
  profit: 840,
},
{
  productId: 34,
  menu: 'ランチメニュー',
  category: 'メイン料理',
  subCategory: '肉料理',
  productName: 'フライドチキンプレート',
  price: 1200,
  cost: 480,
  profit: 720,
},
{
  productId: 35,
  menu: 'ランチメニュー',
  category: 'メイン料理',
  subCategory: '肉料理',
  productName: 'ミートボールスパゲティ',
  price: 1300,
  cost: 520,
  profit: 780,
},
{
  productId: 36,
  menu: 'ランチメニュー',
  category: 'メイン料理',
  subCategory: '魚料理',
  productName: 'サーモン塩焼き定食',
  price: 1600,
  cost: 640,
  profit: 960,
},
{
  productId: 37,
  menu: 'ランチメニュー',
  category: 'メイン料理',
  subCategory: '魚料理',
  productName: 'エビ天丼',
  price: 1500,
  cost: 600,
  profit: 900,
},
{
  productId: 38,
  menu: 'ランチメニュー',
  category: 'メイン料理',
  subCategory: '魚料理',
  productName: '鯖味噌煮ランチ',
  price: 1200,
  cost: 480,
  profit: 720,
},
{
  productId: 39,
  menu: 'ランチメニュー',
  category: 'メイン料理',
  subCategory: '魚料理',
  productName: 'フィッシュ＆チップス',
  price: 1400,
  cost: 560,
  profit: 840,
},
{
  productId: 40,
  menu: 'ランチメニュー',
  category: 'メイン料理',
  subCategory: '魚料理',
  productName: 'マグロステーキランチ',
  price: 1700,
  cost: 680,
  profit: 1020,
},
{
  productId: 41,
  menu: 'ランチメニュー',
  category: 'メイン料理',
  subCategory: 'カレー料理',
  productName: 'チキンカレーランチ',
  price: 1000,
  cost: 400,
  profit: 600,
},
{
  productId: 42,
  menu: 'ランチメニュー',
  category: 'メイン料理',
  subCategory: 'カレー料理',
  productName: '野菜カレーランチ',
  price: 900,
  cost: 360,
  profit: 540,
},
{
  productId: 43,
  menu: 'ランチメニュー',
  category: 'メイン料理',
  subCategory: 'カレー料理',
  productName: 'キーマカレーランチ',
  price: 1100,
  cost: 440,
  profit: 660,
},
{
  productId: 44,
  menu: 'ランチメニュー',
  category: 'メイン料理',
  subCategory: 'カレー料理',
  productName: 'ビーフカレーランチ',
  price: 1200,
  cost: 480,
  profit: 720,
},
{
  productId: 45,
  menu: 'ランチメニュー',
  category: 'メイン料理',
  subCategory: 'カレー料理',
  productName: 'シーフードカレーランチ',
  price: 1300,
  cost: 520,
  profit: 780,
},
{
  productId: 46,
  menu: 'ランチメニュー',
  category: 'メイン料理',
  subCategory: 'パスタ料理',
  productName: 'トマトパスタ',
  price: 1000,
  cost: 400,
  profit: 600,
},
{
  productId: 47,
  menu: 'ランチメニュー',
  category: 'メイン料理',
  subCategory: 'パスタ料理',
  productName: 'カルボナーラ（ランチ）',
  price: 1100,
  cost: 440,
  profit: 660,
},
{
  productId: 48,
  menu: 'ランチメニュー',
  category: 'メイン料理',
  subCategory: 'パスタ料理',
  productName: 'ペストパスタ',
  price: 1100,
  cost: 440,
  profit: 660,
},
{
  productId: 49,
  menu: 'ランチメニュー',
  category: 'メイン料理',
  subCategory: 'パスタ料理',
  productName: 'シーフードパスタランチ',
  price: 1300,
  cost: 520,
  profit: 780,
},
{
  productId: 50,
  menu: 'ランチメニュー',
  category: 'メイン料理',
  subCategory: 'パスタ料理',
  productName: 'ベーコンとほうれん草パスタ',
  price: 1200,
  cost: 480,
  profit: 720,
},
{
  productId: 51,
  menu: 'ランチメニュー',
  category: 'サラダ',
  subCategory: '野菜サラダ',
  productName: 'シーザーサラダ（ランチ）',
  price: 800,
  cost: 320,
  profit: 480,
},
{
  productId: 52,
  menu: 'ランチメニュー',
  category: 'サラダ',
  subCategory: '穀物サラダ',
  productName: 'キヌアサラダ（ランチ）',
  price: 900,
  cost: 360,
  profit: 540,
},
{
  productId: 53,
  menu: 'ランチメニュー',
  category: 'サラダ',
  subCategory: '野菜サラダ',
  productName: 'ギリシャサラダ（ランチ）',
  price: 800,
  cost: 320,
  profit: 480,
},
{
  productId: 54,
  menu: 'ランチメニュー',
  category: 'サラダ',
  subCategory: '野菜サラダ',
  productName: 'コールスローサラダ',
  price: 700,
  cost: 280,
  profit: 420,
},
{
  productId: 55,
  menu: 'ランチメニュー',
  category: 'サラダ',
  subCategory: 'たんぱく質サラダ',
  productName: 'チキンブレストサラダ',
  price: 1000,
  cost: 400,
  profit: 600,
},
{
  productId: 56,
  menu: 'ランチメニュー',
  category: 'ドリンク',
  subCategory: 'ソフトドリンク',
  productName: 'アイスティー',
  price: 400,
  cost: 160,
  profit: 240,
},
{
  productId: 57,
  menu: 'ランチメニュー',
  category: 'ドリンク',
  subCategory: 'ソフトドリンク',
  productName: 'レモネード',
  price: 400,
  cost: 160,
  profit: 240,
},
{
  productId: 58,
  menu: 'ランチメニュー',
  category: 'ドリンク',
  subCategory: 'ソフトドリンク',
  productName: 'コーヒー',
  price: 500,
  cost: 200,
  profit: 300,
},
{
  productId: 59,
  menu: 'ランチメニュー',
  category: 'ドリンク',
  subCategory: 'ソフトドリンク',
  productName: '緑茶',
  price: 400,
  cost: 160,
  profit: 240,
},
{
  productId: 60,
  menu: 'ランチメニュー',
  category: 'ドリンク',
  subCategory: 'ソフトドリンク',
  productName: 'アップルジュース',
  price: 400,
  cost: 160,
  profit: 240,
}
] as const;
